[[buildpacks]]
  id = "org.cloudfoundry.buildpacks.rust"
  uri = "file:///tmp/rust-cnb_b53b02098662d6c29a69c40e" # URIs without schemes are read as paths relative to builder.toml
  latest = true

[[groups]]
  [[groups.buildpacks]]
    id = "org.cloudfoundry.buildpacks.rust"
    version = "0.0.1"

